name: pull-request
run-name: Build on pull request.

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
