name: pull-request
run-name: Checks on pull request.

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release

  trunk-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
